### ISSUE TITLE
Constantly maxes out one core of CPU

### ISSUE THREAD

**Issue by HexCodeFFF** [jkcoxson/netmuxd#17]
![47034EF6-AB75-45D2-9B66-D9A917B9B112](https://user-images.githubusercontent.com/35177464/181210053-837cf83a-979d-4ec5-906b-6640bb7e1e0c.jpeg)
![67D0D7EB-CA83-4214-A172-BB750AAFDBB1](https://user-images.githubusercontent.com/35177464/181210059-059d6282-af54-49d4-8269-77421f00efb3.jpeg)

Alongside it, I’m running usbmuxd, alt-anisette-server, and AltServer-Linux via tmux 

it *works* and still works when I use cpulimit but this is weird behavior

**Comment by HexCodeFFF** [comment]
Pardon some of the clipping of numbers on the screenshot, my ssh client doesn’t properly monospace the Braille that Btop++ uses. C1 is at 100% in that screenshot.

**Comment by HexCodeFFF** [comment]
And this behavior is unchanging wether a device is being refreshed or not or even if there is no device on the network

**Comment by jkcoxson** [comment]
Interesting. What build are you using?

**Comment by HexCodeFFF** [comment]
I believe the latest x86 one from the releases page

**Comment by jkcoxson** [comment]
That's pretty old, I'll update the release. Please try it once I do, as the event loop has changed significantly since April 20th.

**Comment by HexCodeFFF** [comment]
Any updates on this? I tried to build it myself but I've never used rust so I have no idea how

**Comment by jkcoxson** [comment]
I’m currently in Alaska, I’ll upload it when I find internet, as I currently only have roaming 3G.

**Comment by HexCodeFFF** [comment]
Any updates?

**Comment by HexCodeFFF** [comment]
nevermind i'm really stupid and building is super simple. built from git master and the CPU usage is very small
uploading my build artifact in case anyone else is struggling
[netmuxd-x86_64.zip](https://github.com/jkcoxson/netmuxd/files/9429075/netmuxd-x86_64.zip)
