### ISSUE TITLE
Start nextmud automatically in the background for AltStore

### ISSUE THREAD

**Issue by Staubgeborener** [jkcoxson/netmuxd#18]
I read the great [tutorial](https://github.com/jkcoxson/netmuxd#altstore) to use nextmud for AltStore-Linux. And its working great! Basically, i run a manjaro server at home, which i use 99% of the time over ssh (1% vnc). Can i run those commands at boot-time and if yes, how? I don't want to run all those commands one after another every time after restarting the system.

**Comment by jkcoxson** [comment]
Maybe like a cron or something to start a screen? I have no intentions to turn this into a systemctl process or anything like that, netmuxd runs on more platforms than just Linux.
