### ISSUE TITLE
Stuck on Starting mDNS discovery

### ISSUE THREAD

**Issue by blackpager** [jkcoxson/netmuxd#2]
Couldn't get pass Starting mDNS discovery

**Comment by jkcoxson** [comment]
I'm gonna need a bit more info than this to fix stuff.
1. Are you running as root? (aka use sudo)
2. What platform? (OS/ARCH)
3. Maybe a screenshot

**Comment by blackpager** [comment]
Oh sorry.  Yeah I used sudo root.
Ubuntu x86_64
Here’s the screenshot.

![9D14F1B7-CF4A-4067-9360-CCDEA73543FF](https://user-images.githubusercontent.com/66980231/163747051-cff93fb3-cdb5-446e-8ca0-1ba02aa595d6.jpeg)

**Comment by jkcoxson** [comment]
Hmmm do you have another muxer like usbmuxd or usbmuxd2 running? If so, you’ll need to stop them because they both want the same socket.

**Comment by blackpager** [comment]
No, I do not.  But I’ll double check.

**Comment by jkcoxson** [comment]
I have released a new version with some fixes. Please try it out, and if this is still a problem run with RUST_LOGS=netmuxd environment variable

**Comment by jkcoxson** [comment]
Is this still an issue?
