### ISSUE TITLE
cargo build has errors

### ISSUE THREAD

**Issue by vinz2k** [jkcoxson/netmuxd#23]
Hello 

I try command cargo build but I have 3 errors : 

error: failed to run custom build command for `plist_plus v0.2.0
error: failed to run custom build command for `rusty_libimobiledevice v0.1.6`
error: failed to run custom build command for `avahi-sys v0.10.0`

Could you help ?

Here is the whole output : 

[v2k@v2k-pc netmuxd]$ cargo build
   Compiling avahi-sys v0.10.0
   Compiling plist_plus v0.2.0
   Compiling rusty_libimobiledevice v0.1.6
   Compiling derive_builder v0.9.0
error: failed to run custom build command for `plist_plus v0.2.0`

Caused by:
  process didn't exit successfully: `/home/v2k/netmuxd/target/debug/build/plist_plus-1eabfe7ed2809394/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-changed=build.rs
  running: "sh" "-c" "exec \"$0\" \"$@\"" "/home/v2k/netmuxd/target/debug/build/plist_plus-fa950ccace0b6176/out/libplist/configure" "--prefix=/home/v2k/netmuxd/target/debug/build/plist_plus-fa950ccace0b6176/out" "--disable-shared" "--enable-static" "--without-cython"

  --- stderr
  /home/v2k/netmuxd/target/debug/build/plist_plus-fa950ccace0b6176/out/libplist/configure: ligne 1: /home/v2k/netmuxd/target/debug/build/plist_plus-fa950ccace0b6176/out/libplist/configure: Aucun fichier ou dossier de ce type
  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 127

  build script failed, must exit now', /home/v2k/.cargo/registry/src/github.com-1ecc6299db9ec823/autotools-0.2.5/src/lib.rs:715:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `rusty_libimobiledevice v0.1.6`

Caused by:
  process didn't exit successfully: `/home/v2k/netmuxd/target/debug/build/rusty_libimobiledevice-2570397a947ff237/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-changed=build.rs
  cargo:rustc-link-search=native=/home/v2k/netmuxd/target/debug/build/openssl-sys-949371a4c813f8a7/out/openssl-build/install/lib

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/v2k/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty_libimobiledevice-0.1.6/build.rs:143:84
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to run custom build command for `avahi-sys v0.10.0`

Caused by:
  process didn't exit successfully: `/home/v2k/netmuxd/target/debug/build/avahi-sys-031747a4b3de6105/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=avahi-client
  cargo:rustc-link-lib=avahi-common

  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/v2k/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.55.1/src/lib.rs:1896:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by jkcoxson** [comment]
Do you have git installed?

**Comment by vinz2k** [comment]
(sorry for the French language)

**Comment by jkcoxson** [comment]
Make sure to [install these build dependencies](https://github.com/libimobiledevice/libimobiledevice#installation--getting-started)

**Comment by vinz2k** [comment]
Ok i've installed the maximum I could and now I'm still stuck with this only one error (others errors has disappeared) : 

[v2k@v2k-pc netmuxd]$ cargo build
   Compiling avahi-sys v0.10.0
   Compiling zeroconf v0.10.5
   Compiling netmuxd v0.1.3 (/home/v2k/netmuxd)
error[E0432]: unresolved import `rusb`
 --> src/test.rs:3:5
  |
3 | use rusb::{Device, UsbContext};
  |     ^^^^ use of undeclared crate or module `rusb`

error[E0433]: failed to resolve: use of undeclared crate or module `rusb`
  --> src/test.rs:16:21
   |
16 |     let reg: Result<rusb::Registration<rusb::Context>, rusb::Error> = rusb::HotplugBuilder::new()
   |                     ^^^^ use of undeclared crate or module `rusb`

error[E0433]: failed to resolve: use of undeclared crate or module `rusb`
  --> src/test.rs:16:40
   |
16 |     let reg: Result<rusb::Registration<rusb::Context>, rusb::Error> = rusb::HotplugBuilder::new()
   |                                        ^^^^ use of undeclared crate or module `rusb`

error[E0433]: failed to resolve: use of undeclared crate or module `rusb`
  --> src/test.rs:16:56
   |
16 |     let reg: Result<rusb::Registration<rusb::Context>, rusb::Error> = rusb::HotplugBuilder::new()
   |                                                        ^^^^ use of undeclared crate or module `rusb`

error[E0433]: failed to resolve: use of undeclared crate or module `rusb`
  --> src/test.rs:16:71
   |
16 |     let reg: Result<rusb::Registration<rusb::Context>, rusb::Error> = rusb::HotplugBuilder::new()
   |                                                                       ^^^^ use of undeclared crate or module `rusb`

error[E0433]: failed to resolve: use of undeclared crate or module `rusb`
  --> src/test.rs:29:21
   |
29 | impl<T: UsbContext> rusb::Hotplug<T> for Handler {
   |                     ^^^^ use of undeclared crate or module `rusb`

error[E0433]: failed to resolve: use of undeclared crate or module `rusb`
 --> src/test.rs:9:25
  |
9 |     let context = rusb::Context::new().unwrap();
  |                         ^^^^^^^ not found in `rusb`
  |
help: consider importing one of these items
  |
3 | use core::task::Context;
  |
3 | use futures_util::task::Context;
  |
3 | use std::task::Context;
  |
help: if you import `Context`, refer to it directly
  |
9 -     let context = rusb::Context::new().unwrap();
9 +     let context = Context::new().unwrap();
  |

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `netmuxd` due to 7 previous errors
warning: build failed, waiting for other jobs to finish...
[v2k@v2k-pc netmuxd]$

**Comment by vinz2k** [comment]
ok i ve found by using --bin netmuxd in your answer of another topic
