### ISSUE TITLE
thread 'tokio-runtime-worker' panicked 

### ISSUE THREAD

**Issue by maxduke** [jkcoxson/netmuxd#4]
Starting netmuxd
Starting mDNS discovery
Listening on /var/run/usbmuxd
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/central_data.rs:113:46
stack backtrace:
   0:     0x7f383908780d - std::backtrace_rs::backtrace::libunwind::trace::hee598835bc88d35b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f383908780d - std::backtrace_rs::backtrace::trace_unsynchronized::h9cdc730ba5cf5d72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f383908780d - std::sys_common::backtrace::_print_fmt::h75aeaf7ed30e43fa
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f383908780d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h606862f787600875
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f38390a6b9c - core::fmt::write::he803f0f418caf762
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/fmt/mod.rs:1190:17
   5:     0x7f3839080f28 - std::io::Write::write_fmt::h70bc45872f37e7bb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/io/mod.rs:1657:15
   6:     0x7f3839089a87 - std::sys_common::backtrace::_print::h64d038cf8ac3e13e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f3839089a87 - std::sys_common::backtrace::print::h359300b4a7fccf65
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f3839089a87 - std::panicking::default_hook::{{closure}}::hf51be35e2f510149
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:295:22
   9:     0x7f3839089750 - std::panicking::default_hook::h03ca0f22e1d2d25e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:314:9
  10:     0x7f383908a1d9 - std::panicking::rust_panic_with_hook::h3b7380e99b825b63
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:698:17
  11:     0x7f3839089ec7 - std::panicking::begin_panic_handler::{{closure}}::h8e849d0710154ce0
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:588:13
  12:     0x7f3839087cd4 - std::sys_common::backtrace::__rust_end_short_backtrace::hedcdaddbd4c46cc5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x7f3839089bd9 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
  14:     0x7f3838d973e3 - core::panicking::panic_fmt::he1bbc7336d49a357
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
  15:     0x7f3838d97473 - core::result::unwrap_failed::h719f957ed74f93fd
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
  16:     0x7f3838e38360 - core::result::Result<T,E>::unwrap::hfcc0f7a10b4ca825
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1065:23
  17:     0x7f3838e16bb0 - netmuxd::central_data::CentralData::get_udid::h95cc87b418f62a28
                               at /opt/data/compile/netmuxd/src/central_data.rs:113:22
  18:     0x7f3838deaa18 - netmuxd::mdns::discover::{{closure}}::h282084f9ff14588c
                               at /opt/data/compile/netmuxd/src/mdns.rs:44:31
  19:     0x7f3838e36c3b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hdd8bb5633ac5180a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  20:     0x7f3838df9c1a - netmuxd::main::{{closure}}::{{closure}}::ha08f1ef21a6a4378
                               at /opt/data/compile/netmuxd/src/main.rs:73:35
  21:     0x7f3838e355db - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h1cb38d7213e5c52c
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  22:     0x7f3838e0b0e4 - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::hd16f6a257644ae8e
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:161:17
  23:     0x7f3838ddb745 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hf928678f0a307061
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
  24:     0x7f3838e0a827 - tokio::runtime::task::core::CoreStage<T>::poll::haa81e36277878a3b
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:151:13
  25:     0x7f3838dc00fa - tokio::runtime::task::harness::poll_future::{{closure}}::hc3153e0aa1611e1a
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:467:19
  26:     0x7f3838d9b943 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc0aefc4925aae597
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:271:9
  27:     0x7f3838de3cd0 - std::panicking::try::do_call::h1da17aa78254bf85
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  28:     0x7f3838de9e4b - __rust_try
  29:     0x7f3838de0e4a - std::panicking::try::h9572beeaa12af836
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  30:     0x7f3838dfd02a - std::panic::catch_unwind::h26f0699d658d2b47
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  31:     0x7f3838dbe45b - tokio::runtime::task::harness::poll_future::h30927fcc7451796e
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:455:18
  32:     0x7f3838dae229 - tokio::runtime::task::harness::Harness<T,S>::poll_inner::he8637acdf416a049
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:103:27
  33:     0x7f3838daa623 - tokio::runtime::task::harness::Harness<T,S>::poll::h7b10356ed3a0692f
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:57:15
  34:     0x7f3838da10a0 - tokio::runtime::task::raw::poll::h79bfd382faaaab09
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:128:5
  35:     0x7f3838fc483f - tokio::runtime::task::raw::RawTask::poll::h2f4d35404f47cff4
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:80:18
  36:     0x7f3838fa8de2 - tokio::runtime::task::LocalNotified<S>::run::h9bc2a7e7a3dbc1f5
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/mod.rs:347:9
  37:     0x7f3838fe8df2 - tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}::hc73f46389c59e9df
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:425:13
  38:     0x7f3838f6faad - tokio::coop::with_budget::{{closure}}::h92cdadc9add22e22
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  39:     0x7f3838ffd25b - std::thread::local::LocalKey<T>::try_with::h5f963af2b83e5e33
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:413:16
  40:     0x7f3838ffc58e - std::thread::local::LocalKey<T>::with::h469bcbf78270ed9b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:389:9
  41:     0x7f3838fe8cfb - tokio::coop::with_budget::h9b932edde8994031
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  42:     0x7f3838fe8cfb - tokio::coop::budget::h93ebcdda6d676e85
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  43:     0x7f3838fe8cfb - tokio::runtime::thread_pool::worker::Context::run_task::h4ae91b944c546608
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:424:9
  44:     0x7f3838fe85c6 - tokio::runtime::thread_pool::worker::Context::run::h597f27500411bdd2
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:391:24
  45:     0x7f3838fe83c3 - tokio::runtime::thread_pool::worker::run::{{closure}}::h6a6ab5a0c4fe50bb
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:376:17
  46:     0x7f3838f8c447 - tokio::macros::scoped_tls::ScopedKey<T>::set::h23b0a8e6497fe141
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/scoped_tls.rs:61:9
  47:     0x7f3838fe82ef - tokio::runtime::thread_pool::worker::run::h104b19ccb5b0fc2f
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:373:5
  48:     0x7f3838fe816b - tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}::h01f45f3e42268898
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/worker.rs:352:45
  49:     0x7f3838fddffa - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::he5ad06d5cecb5ca9
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/task.rs:42:21
  50:     0x7f3838fe6345 - tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}::h77aed5aa3b39f3aa
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:161:17
  51:     0x7f3838f9cad5 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::ha55145bbdf66ef35
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
  52:     0x7f3838fe61c8 - tokio::runtime::task::core::CoreStage<T>::poll::h82d22b627ceed3a6
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:151:13
  53:     0x7f3838ffa24e - tokio::runtime::task::harness::poll_future::{{closure}}::h0cf14561713e77e8
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:467:19
  54:     0x7f3838f775b3 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h2f29f9eb7f53fc29
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:271:9
  55:     0x7f383900e412 - std::panicking::try::do_call::ha507141770ccb209
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  56:     0x7f383900f68b - __rust_try
  57:     0x7f383900da1a - std::panicking::try::hd169aa0ff4b43479
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  58:     0x7f3838ffe8eb - std::panic::catch_unwind::h716e016de05aab56
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  59:     0x7f3838ff9cdc - tokio::runtime::task::harness::poll_future::h29aad04307fe941e
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:455:18
  60:     0x7f3838ff6c0c - tokio::runtime::task::harness::Harness<T,S>::poll_inner::h0a219ad128e72a65
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:103:27
  61:     0x7f3838ff69c4 - tokio::runtime::task::harness::Harness<T,S>::poll::hc541b2cc2e66cb02
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:57:15
  62:     0x7f3838fc4992 - tokio::runtime::task::raw::poll::h37954691c8ecb543
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:128:5
  63:     0x7f3838fc483f - tokio::runtime::task::raw::RawTask::poll::h2f4d35404f47cff4
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:80:18
  64:     0x7f3838fa8e94 - tokio::runtime::task::UnownedTask<S>::run::he546c12c22c52002
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/mod.rs:384:9
  65:     0x7f3838f96c47 - tokio::runtime::blocking::pool::Task::run::hac1e1c85d25438d0
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:91:9
  66:     0x7f3838f990d9 - tokio::runtime::blocking::pool::Inner::run::h4b7fdd49def0273c
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:308:17
  67:     0x7f3838f9852c - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::h9fd1f3d9bc769b80
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/blocking/pool.rs:288:17
  68:     0x7f3838f7b05c - std::sys_common::backtrace::__rust_begin_short_backtrace::h079edb8deac51f9a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys_common/backtrace.rs:122:18
  69:     0x7f3838fe1f31 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hf83f84a80c4d6acb
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/mod.rs:498:17
  70:     0x7f3838f776b1 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h760a105c0482bb25
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panic/unwind_safe.rs:271:9
  71:     0x7f383900e24c - std::panicking::try::do_call::h701a537c917a0b56
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:492:40
  72:     0x7f383900f68b - __rust_try
  73:     0x7f383900d1d1 - std::panicking::try::h8c41df984661dfbc
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:456:19
  74:     0x7f3838ffe781 - std::panic::catch_unwind::h3c30f06ee3c05a24
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panic.rs:137:14
  75:     0x7f3838fe1d45 - std::thread::Builder::spawn_unchecked_::{{closure}}::hbef7d74aebb1e230
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/mod.rs:497:30
  76:     0x7f3838fa1d2f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h75bac3f3cc3d6877
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
  77:     0x7f383908ea33 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf70ac038171e3e1a
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  78:     0x7f383908ea33 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::he6690128792365ad
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/alloc/src/boxed.rs:1853:9
  79:     0x7f383908ea33 - std::sys::unix::thread::Thread::new::thread_start::ha07928d93d5a5ec9
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/sys/unix/thread.rs:108:17
  80:     0x7f3838cdc609 - start_thread
  81:     0x7f3838aac163 - clone
  82:                0x0 - <unknown>

**Comment by maxduke** [comment]
Is it mandatory to pass an argument to "--plist-storage"?

**Comment by jkcoxson** [comment]
You need to pair your device first through a different muxer and a USB cable. Usbmuxd will work fine.

**Comment by jkcoxson** [comment]
/var/lib/lockdown
