### ISSUE TITLE
Cannot find some devices in mdns

### ISSUE THREAD

**Issue by zeyugao** [jkcoxson/netmuxd#7]
According to https://github.com/dylanmckay/mdns/issues/12, mdns crate can miss some devices. As for me, it will miss my iPhone, but it can find my iPad.

I reimplement the mdns.rs using https://docs.rs/zeroconf/latest/zeroconf/index.html, which is a wrapper of avahi, which can discover all devices.

At https://github.com/zeyugao/netmuxd/tree/master, but it cannot be compiled statically. So making it hard to run on tiny device. I leave a Dockerfile in the repo which can be cross compiled with the aid of docker buildx.

And because it cannot be statically compiled, I didn't create a pull request for that. But if you want, I will.

**Comment by jkcoxson** [comment]
I think implementing zeroconf would be a great alternative, but not a replacement to mDNS. Maybe you could add it as a cargo feature so users can choose at compile time?

**Comment by adityasanghvi** [comment]
How can I better report this issue? netmuxd successfully finds and add my iPhone X but with the same process, it doesn't add my iPhone 13.

iPhone 13 is recognized, paired and works normally on USB

**Comment by zeyugao** [comment]
@adityasanghvi  This issue is related to the mdns crate, you can open an issue in https://github.com/dylanmckay/mdns with the result from `avahi-browser` and https://github.com/dylanmckay/mdns/blob/master/examples/http_discovery.rs. Just like https://github.com/dylanmckay/mdns/issues/12

As a workaround, you can pull the docker image from https://github.com/zeyugao/netmuxd/pkgs/container/netmuxd. Run it with `--host` or copy `/usr/local/bin/netmuxd` from docker image, install `libavahi-client-dev` as dependency. Because I built the docker image with Ubuntu 20.04 and cannot compile the program statically. So maybe there are issues when running on older linux distribution.

@jkcoxson Moreover, the mdns crate will not find anything when running on the device with multiple network interfaces, such as raspberry pi.

**Comment by jkcoxson** [comment]
Okay, makes sense to replace mDNS then with zeroconf.

**Comment by jkcoxson** [comment]
@zeyugao did you say you were gonna make a PR with the zeroconf backend? I think it’s better that it works than being completely static.

**Comment by zeyugao** [comment]
@jkcoxson Well, I was just preparing for the pr when you commented.

**Comment by Centterm** [comment]
@jkcoxson thanks a lot for the work on netmuxd. I was also not able to find my iPhone via [release v.0.1.2](https://github.com/jkcoxson/netmuxd/releases/tag/v0.1.2) so I thought I might give the latest changes of @zeyugao PR a try (which are not released yet) and pulled your [docker build](https://github.com/jkcoxson/netmuxd/pkgs/container/netmuxd) and simply extracted the `netmuxd-zeroconf` binary from the image to my host. 

Discovery and applications (e.g. Altserver) work fine but after a while I get a lot of the following errors and I have to restart netmuxd (no need to reconnect via USB).
```
Failed to create heartbeat client for udid PlaceholderUUID: UnknownError
``` 
Any idea what might be the problem?

**Comment by jkcoxson** [comment]
@Centterm please open a new issue for this so other people can find it.

**Comment by zeyugao** [comment]
@jkcoxson Can I generate a pairing config and use it on another device?

**Comment by jkcoxson** [comment]
Yes

**Comment by jkcoxson** [comment]
If you want to join the discord where we all work on this stuff, it’s at http://discord.jitstreamer.com

**Comment by Staubgeborener** [comment]
@zeyugao 
Building the dockerfile in the netmuxd directory leads to this error:

```
Step 11/18 : COPY Cargo.toml netmuxd
COPY failed: file not found in build context or excluded by .dockerignore: stat Cargo.toml: file does not exist
```
But Cargo.toml (and Cargo.lock) is in the correct directory like the Dockerfile...?

**Comment by zeyugao** [comment]
@Staubgeborener The Github Action which uses the Dockerfile is succeeding. I have no idea what it is complaining about. Did you modify the source code or download and build directly.

**Comment by Staubgeborener** [comment]
```
git clone https://github.com/jkcoxson/netmuxd/
cd ./netmuxd
docker build - < Dockerfile
```

**Comment by zeyugao** [comment]
@Staubgeborener You should use `docker build .` to use current directory as context. Or `docker build -f - . < Dockerfile`

As for the building section, which command are you using for building? The output file should be located in `target/debug/netmuxd` when using `cargo build` and `target/release/netmuxd` when `cargo build --release`

**Comment by Staubgeborener** [comment]
yeah, `docker build .` did the trick. It successfully creates an image. But after running it `docker run -dit container_id` i'm a bit confused. I exec the container `docker exec -it container-id /bin/bash` (yes, i used the correct container id) and `cat /proc/version` shows me a manjaro system instead ubuntu (my host is a manjaro), also i can't see the netmuxd files (also no zeroconf, etc) or any folder from the Dockerfile like `output`. So what am i missing? Do i need to build everything before or is cloning the repository and building the docker container from the Dockerfile enough?

**Comment by zeyugao** [comment]
@Staubgeborener Docker is a container but not a virtual machine. It will not ship with the kernel, but share the kernel with host, the manjaro in your case. The ubuntu in the Dockerfile means the rootfs from ubuntu, but not the kernel.

The Dockerfile takes advantage of [multistage building](https://docs.docker.com/develop/develop-images/multistage-build/). The final image will be pushed to docker registry but not the building layers which contain a lot of intermediate files. So when users pulling from docker registry, the image will be minimized but still runnable.

The built binary is located in `/usr/local/bin/` in the container. See the last line in Dockerfile:

```
COPY --from=builder /output/ /usr/local/bin/
```

The ReadMe is somewhat out of date. To address the error you encounter, you should clone https://github.com/jkcoxson/mdns next to the netmuxd folder.

As for how to use netmuxd in docker. Maybe you should run container with `--net=host` and mount `/var/lib/lockdown` into container.

**Comment by Staubgeborener** [comment]
Yeah i think it's working now:
`sudo docker run -dit --net=host -v /var/lib/lockdown:/var/lib/lockdown container-id`

```
root@nuc:/work/netmuxd/target/release# ./netmuxd 
Starting netmuxd
Listening on /var/run/usbmuxd
Starting mDNS discovery for _apple-mobdev2._tcp.local with mdns
Adding device UUID-OF-IPHONE
Removing UUID-OF-IPHONE
Adding device UUID-OF-IPHONE
```
When i unlock my iPhone i'll get `Adding device UUID-OF-IPHONE`, when locking the iPhone i'll get `Removing UUID-OF-IPHONE`. So `--net=host` seems to be good. 
But all in all, i hoped to get rid of [this](https://github.com/jkcoxson/netmuxd/issues/10#issuecomment-1200373914) issue. After starting nextmuxd (no matter if inside docker or native on host) and starting AltServer i'll get the very famous `Failed to handle request:AltServer could not find the device.` message. Which is weird, because netmuxd recognize the iPhone and also AltServer recognize the iPhone if i press "update" in AltStore:
```
[...]
Finished handling request!
Other Socket:7. Port: 62420. Error: 0
Receiving request size...
Checking socket: 7
Received bytes: 4(of 4)
Receiving 33765 bytes...
Checking socket: 7
Received bytes: 1448(of 33765)
Checking socket: 7
Received bytes: 5544(of 33765)
Checking socket: 7
Received bytes: 9640(of 33765)
Checking socket: 7
Received bytes: 10136(of 33765)
Checking socket: 7
Received bytes: 11584(of 33765)
Checking socket: 7
Received bytes: 13032(of 33765)
Checking socket: 7
Received bytes: 17128(of 33765)
Checking socket: 7
Received bytes: 21224(of 33765)
Checking socket: 7
Received bytes: 25320(of 33765)
Checking socket: 7
Received bytes: 29416(of 33765)
Checking socket: 7
Received bytes: 33512(of 33765)
Checking socket: 7
Received bytes: 33765(of 33765)
Represented Value: 86
Sent Bytes Count: 4 (4)
Sent Data: 4 Bytes
Failed to handle request:AltServer could not find the device.
Sent Bytes Count: 86 (86)
Sent Data: 86 Bytes
```
