### ISSUE TITLE
Exception on thread tokyo-runtime-worker

### ISSUE THREAD

**Issue by ccatina** [jkcoxson/netmuxd#8]
Hello!
I'm trying to run netmuxd on raspberry pi with Altstore. I'm using release build for arm-v7 for both applications. 
My steps: 
1. Run netmuxd with command `RUST_BACKTRACE=1 ./netmuxd-armv7 --disable-unix --host 127.0.0.1`
2. Run Altstore with command `./AltServer-armv7 `
3. In netmuxd I received this error (screen 1) <img width="870" alt="Снимок экрана 2022-04-29 в 16 10 15" src="https://user-images.githubusercontent.com/52932617/165950728-62750fc4-ef1d-4d37-8df3-80c61ce866fe.png">

**Comment by jkcoxson** [comment]
This was supposedly fixed in #6, can you rebuild and try again?

**Comment by jkcoxson** [comment]
Please re-open if this is still an issue

**Comment by jkcoxson** [comment]
Yes, that's a different issue. It's saying whatever address you're trying to bind to is already used by another program.
